pricechanges/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeItems.as_view(), name='home'),
    path('add_item_error/', views.AddItemError.as_view(), name='add_item_error'),
    path('add_item/', views.AddItem.as_view(), name='add_item'),
    path('update_item/<int:pk>/', views.UpdateItem.as_view(), name='update_item'),
    path('contact/', views.contact, name='contact'),
    path('items/<slug:item_slug>/', views.ShowItem.as_view(), name='item'),
    path('marketplace/<slug:mtplace_slug>/', views.ShowMenu.as_view(), name='marketplace'),
    path('tag/<slug:tag_slug>/', views.ShowTagItems.as_view(), name='tag'),
]

pricechanges/pricechanges/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
] + debug_toolbar_urls()


handler404 = page_not_found

pricechanges/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views
from .forms import UserPasswordChangeForm

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUsers.as_view(), name='login'),
    path('logout/', views.logout_users, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
                                                        success_url=reverse_lazy("users:password_change_done"),
                                                        template_name="users/password_change_form.html"),
         name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
]

pricechanges/users/models.py
from django.db import models

pricechanges/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': "Имя",
            'last_name': "Фамилия",
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

pricechanges/users/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm


class LoginUsers(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


def logout_users(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя"}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

pricechanges/users/templates/users/login.html
{% load static %}
{% load main_tags %}
<!DOCTYPE html>
<html>
<head>
    <style>
       .market {
  color: #993653;
}
    </style>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'main/images/main.ico' %}" type="image/x-icon"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4 text-center">Авторизация</h2>
                <div class="card">
                   <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}" />
                        <div class="mb-3">
                         {% if form.non_field_errors %}
                          <div class="alert alert-danger" role="alert">
                                 {{ form.non_field_errors }}
                          </div>
                         {% endif %}
                           </div>
                        {% for f in form %}
                            <div class="mb-3">
                              <label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>
                              {{ f }}
                              {% if f.errors %}
                              <div class="text-danger">
                                 {{ f.errors }}
                              </div>
                              {% endif %}
                            </div>
                        {% endfor %}
                       <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary" style="width: 40%; margin: auto;">Войти</button>
                       </div>
                        <div class="mt-3 text-center">
                        <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                        </div>
                        <div class="mt-3 text-center">
                        <a href="{% url 'users:register' %}">Регистрация</a>
                        </div>
                    </form>
                 </div>
                </div>
            </div>
        </div>
    </div>

    <p class="text-lowercase text-center"></p>
    <div class="container alert alert-danger" role="alert" style="width: 30%; margin: auto; margin-top: 50px; text-align: center;">
    Сервис доступен только авторизованным пользователям.
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

pricechanges/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

pricechanges/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

pricechanges/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

pricechanges/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

pricechanges/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

pricechanges/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

pricechanges/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

pricechanges/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Профиль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

pricechanges/users/templates/users/register.html
{% load static %}
{% load main_tags %}
<!DOCTYPE html>
<html>
<head>
    <style>
       .market {
  color: #993653;
}
    </style>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'main/images/main.ico' %}" type="image/x-icon"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="mb-4 text-center">Регистрация</h2>
                <div class="card">
                   <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}" />
                        <div class="mb-3">
                         {% if form.non_field_errors %}
                          <div class="alert alert-danger" role="alert">
                                 {{ form.non_field_errors }}
                          </div>
                         {% endif %}
                           </div>
                        {% for f in form %}
                            <div class="mb-3">
                              <label for="{{ f.id_for_label }}" class="form-label">{{ f.label }}</label>
                              {{ f }}
                              {% if f.errors %}
                              <div class="text-danger">
                                 {{ f.errors }}
                              </div>
                              {% endif %}
                            </div>
                        {% endfor %}
                       <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary" style="width: 40%; margin: auto;">Зарегистрироваться</button>
                       </div>
                        <div class="mt-3 text-center">
                            <p style="margin: auto; margin-top: 20px; text-align: center;">Уже есть аккаунт?</p>
                            <a href="{% url 'users:login' %}">Вход</a>
                        </div>
                    </form>
                 </div>
                </div>
            </div>
        </div>
    </div>

    <p class="text-lowercase text-center"></p>
    <div class="container alert alert-danger" role="alert" style="width: 30%; margin: auto; margin-top: 50px; text-align: center;">
    Сервис доступен только зарегистрированным пользователям.
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

pricechanges/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Добро пожаловать!</h1>

<p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой
  <a href="{% url 'users:login' %}">ссылке</a>
</p>
{% endblock %}