pricechanges/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeItems.as_view(), name='home'),
    path('add_item_error/', views.AddItemError.as_view(), name='add_item_error'),
    path('add_item/', views.AddItem.as_view(), name='add_item'),
    path('update_item/<int:pk>/', views.UpdateItem.as_view(), name='update_item'),
    path('contact/', views.contact, name='contact'),
    path('items/<slug:item_slug>/', views.ShowItem.as_view(), name='item'),
    path('marketplace/<slug:mtplace_slug>/', views.ShowMenu.as_view(), name='marketplace'),
    path('tag/<slug:tag_slug>/', views.ShowTagItems.as_view(), name='tag'),
]

pricechanges/pricechanges/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
] + debug_toolbar_urls()


handler404 = page_not_found

pricechanges/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views
from .forms import UserPasswordChangeForm

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUsers.as_view(), name='login'),
    path('logout/', views.logout_users, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
                                                        success_url=reverse_lazy("users:password_change_done"),
                                                        template_name="users/password_change_form.html"),
         name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),
]

pricechanges/templates/base.html
{% load static %}
{% load main_tags %}
<!DOCTYPE html>
<html>
<head>
    <style>
       .market {
  color: #993653;
}
    </style>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'main/images/main.ico' %}" type="image/x-icon"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% block mainmenu %}
	<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-secondary">Главная</a></li>
		{% for m in nav %}
        <li><a href="{% url m.url_name %}" class="nav-link px-2 link-dark">{{m.title}}</a></li>
		{% endfor %}
      </ul>
	  {% if user.is_authenticated %}
      <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2"><a class="nav-link" href="{% url 'users:profile' %}">{{user.username}}</a></button>
        <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'users:logout' %}">Выйти</a></button>
      </div>
	  {% else %}
	  <div class="col-md-3 text-end">
		<button type="button" class="btn btn-outline-primary me-2"><a class="nav-link" href="{% url 'users:login' %}">Войти</a></button>
        <button type="button" class="btn btn-primary"><a class="nav-link" href="{% url 'users:register' %}">Регистрация</a></button>
	  </div>
		{% endif %}
		{% endblock %}
    </header>

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-1 px-0 bg-white ">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <h5 class="market">Маркетплейсы</h5>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="/" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Все товары</span>
                        </a>
                    </li>
                    {% show_menu %}
					{% show_tags %}
			</div>
		</div>
		<div class="col py-3">
           {% block content %}
            {% endblock %}
        </div>
	</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>